---
title: "Chapter 6. Tables"
output: html_notebook
---
```{r}
counts <- rpois(1000, 0.6)
table(counts)
```

```{r}
infections <- read.table(file.path(getwd(), "data/infection.txt"), header = TRUE)
with(infections, table(infected, sex))
with(infections, table(sex, infected))
```

```{r}
data <- read.table(file.path(getwd(), "data/daphnia.txt"), header = TRUE)
with(data, tapply(Growth.rate,Detergent,mean))
```
```{r}
with(data, tapply(Growth.rate,Water,mean))
```
```{r}
with(data, tapply(Growth.rate,Daphnia,mean))
```
```{r}
with(data, tapply(Growth.rate,list(Daphnia,Detergent),mean))
```
```{r}
with(data, tapply(Growth.rate,list(Daphnia,Detergent),median))
```
```{r}
with(data, {
  tapply(Growth.rate,list(Daphnia,Detergent), function(x) sqrt(var(x)/length(x)))
})
```
```{r}
with(data, tapply(Growth.rate,list(Daphnia,Detergent,Water),mean))
```
```{r}
with(data, ftable(tapply(Growth.rate,list(Daphnia,Detergent,Water),mean)))
```
```{r}
with(data, {
  ftable(tapply(Growth.rate,list(Daphnia,Detergent,factor(Water,levels=c("Wear","Tyne"))),mean))
})
```
```{r}
with(data, as.data.frame.table(tapply(Growth.rate,list(Detergent,Daphnia),mean)))
```
```{r}
with(data,{
  new<-as.data.frame.table(tapply(Growth.rate,list(Detergent,Daphnia),mean))
  names(new)<-c("detergents","daphina","means")
  head(new)
})
```
```{r}
count.table<-read.table(file.path(getwd(), "data/tabledata.txt"), header=T)
lapply(count.table,function(x)rep(x, count.table$count))
```
```{r}
dbtable<-as.data.frame(lapply(count.table,function(x) rep(x, count.table$count)))
head(dbtable)
dbtable<-dbtable[,-1]
head(dbtable)
```
```{r}
table(dbtable)
```
```{r}
as.data.frame(table(dbtable))
```
```{r}
(counts<-matrix(c(2,2,4,3,1,4,2,0,1,5,3,3),nrow=4))
```
```{r}
prop.table(counts,1)
```
```{r}
prop.table(counts,2)
```
```{r}
prop.table(counts)
```
```{r}
sum(prop.table(counts))
```
```{r}
colSums(prop.table(counts, 2))
```

