---
title: "Chapter 7. Mathematics."
output: html_notebook
---
```{r}
x <- seq(0,10,0.1)
par(mfrow=c(1,2))
y <- exp(x)
plot(y~x,type="l",main="Exponential")
y <- log(x)
plot(y~x,type="l",main="Logarithmic")
```
```{r}
par(mfrow=c(2,2))
x <- seq(0,2*pi,2*pi/100)
y1 <- cos(x)
y2 <- sin(x)
y3 <- tan(x)
y4 <- cos(x)/sin(x)
plot(y1~x,type="l",main="cosine")
plot(y2~x,type="l",main="sine")
plot(y3~x,type="l",ylim=c(-3,3),main="tangent")
plot(y4~x,type="l",ylim=c(-3,3),main="cotangent")
```
```{r}
par(mfrow=c(2,2))
x <- seq(0,1,0.01)
y <- x^0.5
plot(x,y,type="l",main="0<b<1")
y <- x
plot(x,y,type="l",main="b=1")
y <- x^2
plot(x,y,type="l",main="b>1")
y <- 1/x
plot(x,y,type="l",main="b<0")
```
```{r}
x <- seq(0,10,0.1)
y1 <- 2+5*x-0.2*x^2
y2 <- 2+5*x-0.4*x^2
y3 <- 2+4*x-0.6*x^2+0.04*x^3
y4 <- 2+4*x+2*x^2-0.6*x^3+0.04*x^4
par(mfrow=c(2,2))
plot(x,y1,type="l",ylab="y",main="decelerating")
plot(x,y2,type="l",ylab="y",main="humped")
plot(x,y3,type="l",ylab="y",main="inflection")
plot(x,y4,type="l",ylab="y",main="local maximum")
```
```{r}
par(mfrow=c(2,2))
y1 <- x/(2+5*x)
y2 <- 1/(x-2+4/x)
y3 <- 1/(x^2-2+4/x)
plot(x,y1,type="l",ylab="y",main="Michaelis-Menten")
plot(x,y2,type="l",ylab="y",main="shallow hump")
plot(x,y3,type="l",ylab="y",main="steep hump")
```
```{r}
par(mfrow=c(1,1))
t <- seq(0.2,4,0.01)
plot(t,gamma(t),type="l")
abline(h=1,lty=2)
```
```{r}
par(mfrow=c(2,2))
x <- seq(0,10,0.1)
y <- 100/(1+90*exp(-1*x))
plot(x,y,type="l",main="three-parameter logistic")
y <- 20+100/(1+exp(0.8*(3-x)))
plot(x,y,ylim=c(0,140),type="l",main="four-parameter logistic")
x <- -200:100
y <- 100*exp(-exp(0.02*x))
plot(x,y,type="l",main="negative Gompertz")
x <- 0:100
y <- 50*exp(-5*exp(-0.08*x))
plot(x,y,type="l",main="positive Gompertz")
```
```{r}
#par(mfrow=c(2,2))
#1
a <- 10
b <- -0.8
c <- 10
d <- -0.05
y <- a*exp(b*x)+c*exp(d*x)
plot(x,y,main="+ - + -",type="l")
#2
a <- 10
b <- -0.8
c <- 10
d <- 0.05
y <- a*exp(b*x)+c*exp(d*x)
plot(x,y,main="+ - + +",type="l")
#3
a <- 200
b <- 0.2
c <- -1
d <- 0.7
y <- a*exp(b*x)+c*exp(d*x)
plot(x,y,main="+ + - +",type="l")
#4
a <- 200
b <- 0.05
c <- 300
d <- -0.5
y <- a*exp(b*x)+c*exp(d*x)
plot(x,y,main="+ + + -",type="l")
```
```{r}
par(mfrow=c(1,1))
x <- 0:6
plot(x,factorial(x),type="s",main="factorial x",log="y")
```
```{r}
plot(0:8,choose(8,0:8),type="s",main="binomial coefficients")
```
```{r}
curve(pnorm(x),-3,3)
arrows(-1,0,-1,pnorm(-1),col="red")
arrows(-1,pnorm(-1),-3,pnorm(-1),col="green")
```
```{r}
curve(dnorm(x),-3,3)
```
```{r}
par(mfrow=c(2,2))
x <- seq(-3,3,0.01)
y <- exp(-abs(x))
plot(x,y,type="l",main="x")
y <- exp(-abs(x)^2)
plot(x,y,type="l",main="x^2")
y <- exp(-abs(x)^3)
plot(x,y,type="l",main="x^3")
y <- exp(-abs(x)^8)
plot(x,y,type="l",main="x^8")
```
```{r}
print(pnorm(-1.25))
```
```{r}
par(mfrow=c(2,2))
hist(sample(1:6,replace=T,10000),breaks=0.5:6.5,main="",xlab="one die")
a <- sample(1:6,replace=T,10000)
b <- sample(1:6,replace=T,10000)
hist(a+b,breaks=1.5:12.5,main="", xlab="two dice")
c <- sample(1:6,replace=T,10000)
hist(a+b+c,breaks=2.5:18.5,main="", xlab="three dice")
d <- sample(1:6,replace=T,10000)
e <- sample(1:6,replace=T,10000)
hist(a+b+c+d+e,breaks=4.5:30.5,main="", xlab="five dice")
print(paste(c(mean(a+b+c+d+e), sd(a+b+c+d+e))))
lines(seq(1,30,0.1),dnorm(seq(1,30,0.1),17.5937,3.837668)*10000)
```
```{r}
par(mfrow=c(2,2))
curve(dnorm,-3,3,xlab="z",ylab="Probability density",main="Density")
curve(pnorm,-3,3,xlab="z",ylab="Probability",main="Probability")
curve(qnorm,0,1,xlab="p",ylab="Quantile (z)",main="Quantiles")
y <- rnorm(1000)
hist(y,xlab="z",ylab="frequency",main="Random numbers")
```
```{r}
yvals <- rnorm(100)
mean(yvals)
sd(yvals)
yvals <- (yvals - mean(yvals))/sd(yvals)
mean(yvals)
sd(yvals)
```
```{r}
par(mfrow=c(1,1))
fishes <- read.table(file.path(getwd(), "data/fishes.txt"),header=T)
with(fishes,{
  hist(mass, breaks=-0.5:16.5,col="green",main="")
  lines(seq(0,16,0.1),length(mass)*dnorm(seq(0,16,0.1),mean(mass),sqrt(var(mass))))
})
```
```{r}
1-pchisq(14.3,9)
qchisq(1-0.05, 9)
1-pf(2.85,8,12)
qt(0.975,10)
```
```{r}
par(mfrow=c(1,2))
x <- seq(0,30,.25)
plot(x,pchisq(x,3,7.25),type="l",ylab="p(x)",xlab="x")
plot(x,pchisq(x,5,10),type="l",ylab="p(x)",xlab="x")
```
```{r}
#95% confidence interval for variance (s-squared = 10.2 and 8 d.f.)
8*10.2/qchisq(.975,8)
8*10.2/qchisq(.025,8)
```
```{r}
qf(0.95, 2, 18)
x <- seq(0.05,4,0.05)
plot(x,df(x,2,18),type="l",ylab="f(x)",xlab="x")
plot(x,df(x,6,18),type="l",ylab="f(x)",xlab="x")
```
```{r}
par(mfrow=c(1,1))
df <- seq(1,30,.1)
plot(df,qf(.95,df,30),type="l",ylab="Critical F")
lines(df,qf(.95,df,10),lty=2)
```
```{r}
x <- seq(0.01,3,0.01)
plot(x,df(x,1,10),type="l",ylim=c(0,1),ylab="f(x)")
lines(x,df(x,2,10),lty=6,col="red")
lines(x,df(x,5,10),lty=2,col="green")
lines(x,df(x,30,10),lty=3,col="blue")
legend(2,0.9,c("1","2","5","30"),col=(1:4),lty=c(1,6,2,3),title="numerator d.f.")
```
```{r}
curve( (1+x^2)^(-0.5), -3, 3,ylab="t(x)",col="red")
```
```{r}
plot(1:30,qt(0.975,1:30), ylim=c(0,12),type="l",ylab="Students t value",xlab="d.f.",col="red")
abline(h=2,lty=2,col="green")
```
```{r}
xvs <- seq(-4,4,0.01)
plot(xvs,dnorm(xvs),type="l",lty=2,ylab="Probability density",xlab="Deviates")
lines(xvs,dt(xvs,df=5),col="red")
```
```{r}
x <- seq(0.01,4,.01)
par(mfrow=c(2,2))
y <- dgamma(x,.5,.5)
plot(x,y,type="l",col="red",main="alpha = 0.5")
y <- dgamma(x,.8,.8)
plot(x,y,type="l",col="red", main="alpha = 0.8")
y <- dgamma(x,2,2)
plot(x,y,type="l",col="red", main="alpha = 2")
y <- dgamma(x,10,10)
plot(x,y,type="l",col="red", main="alpha = 10")
```
```{r}
qgamma(0.95,2/3,4/3)
```
```{r}
fishes <- read.table(file.path(getwd(),"data/fishes.txt"),header=T)
(rate <- mean(fishes$mass)/var(fishes$mass))
(shape <- rate*mean(fishes$mass))
```
```{r}
par(mfrow=c(1,1))
hist(fishes$mass,breaks=-0.5:16.5,col="green",main="")
lines(seq(0.01,15,0.01),length(fishes$mass)*dgamma(seq(0.01,15,0.01),shape,rate))
```
```{r}
par(mfrow=c(2,2))
x <- seq(0,1,0.01)
fx <- dbeta(x,2,3)
plot(x,fx,type="l",main="a=2 b=3",col="red")
fx <- dbeta(x,0.5,2)
plot(x,fx,type="l",main="a=0.5 b=2",col="red")
fx <- dbeta(x,2,0.5)
plot(x,fx,type="l",main="a=2 b=0.5",col="red")
fx <- dbeta(x,0.5,0.5)
plot(x,fx,type="l",main="a=0.5 b=0.5",col="red")
```
```{r}
par(mfrow=c(1,2))
plot(-200:200,dcauchy(-200:200,0,10),type="l",ylab="p(x)",xlab="x",col="red")
plot(-200:200,dcauchy(-200:200,0,50),type="l",ylab="p(x)",xlab="x",col="red")
```
```{r}
par(mfrow=c(1,2))
plot(seq(-5,5,0.02),dlogis(seq(-5,5,.02)),
type="l",main="Logistic",col="red",xlab="x",ylab="p(x)")
plot(seq(-5,5,0.02),dnorm(seq(-5,5,.02)),
type="l",main="Normal",col="red",xlab="x",ylab="p(x)")
```
```{r}
a <- 3
l <- 1
t <- seq(0,1.8,.05)
ft <- a*l*t^(a-1)*exp(-l*t^a)
plot(t,ft,type="l",col="blue",ylab="f(t) ")
a <- 1
ft <- a*l*t^(a-1)*exp(-l*t^a)
lines(t,ft,type="l",col="red")
a <- 2
ft <- a*l*t^(a-1)*exp(-l*t^a)
lines(t,ft,type="l",col="green")
legend(1.4,1.1,c("1","2","3"),title="alpha",lty=c(1,1,1),col=c(2,3,4))
```

