---
title: "The R Book. Chapter 5"
output: html_notebook
---
```{r}
data("iris")
x1 <- iris$Petal.Length
x2 <- iris$Sepal.Length
y1 <- iris$Petal.Width
y2 <- iris$Sepal.Width
```

```{r}
plot(x1, y1, xlab = "length", ylab = "width", col="red", pch=1)
abline(lm(y1 ~ x1))
points(x2, y2, col="blue", pch=2)
abline(lm(y2 ~ x2))
```

```{r}
plot(c(x1,x2), c(y1,y2), xlab="Explanatory variable", ylab = "Response variable", type = "n")
points(x1, y1, col="red")
points(x2, y2, col="blue", pch=16)
abline(lm(y1 ~ x1))
abline(lm(y2 ~ x2))
```

```{r}
plot(c(x1,x2),c(y1,y2), xlim=range(x1,x2), ylim=range(y1, y2), xlab="Explanatory variable", ylab="Response variable", type="n")
points(x1,y1,col="red")
points(x2,y2,col="blue",pch=16)
abline(lm(y1~x1))
abline(lm(y2~x2))
legend(3, c("petal","sepal"), pch=c(1,16), col=c("red","blue"))
```

```{r}
plot(0:9,0:9,pch=16,type="n",xaxt="n",yaxt="n",ylab="col",xlab="bg")
axis(1,at=1:8)
axis(2,at=1:8)
for (i in 1:8) points(1:8,rep(i,8),pch=c(21,22,24),bg=1:8,col=i)
```

```{r}
plot(c(0,10),c(0,10),type="n",xlab="",ylab="",xaxt="n", yaxt="n")
for (i in 1:8) text(1:8,rep(i,8), LETTERS[i])
```
```{r}
species <- as.numeric(iris$Species)
pchs <- rep(c(1,2,6), times=c(50,50,50))
cols <- rep(c("red", "black", "blue"), times=c(50,50,50))
plot(iris$Sepal.Length, iris$Sepal.Width, type = "n")
for (k in 1:length(species)){
  points(iris$Sepal.Length[k],iris$Sepal.Width[k],pch=pchs[k],col=cols[k])
}
```
```{r}
plot(iris$Petal.Length, iris$Petal.Width)
text(iris$Petal.Length, iris$Petal.Width, labels=as.character(iris$Species), pos=2, offset=0.5,cex=0.5)
```
```{r}
plot(iris$Petal.Length, iris$Petal.Width, pch=16, col=ifelse(iris$Petal.Length>median(iris$Petal.Length),"red","black"))
legend(2,c("iPL>median","iPL<=median"),pch=16,col=c("red","black"))
```
```{r}
x <- runif(15,4, 10)
y <- rnorm(15)
plot(x,y,pch=16)
lines(x,y)
```
```{r}
ordered <- order(x)
plot(x[ordered],y[ordered],pch=16)
lines(x[ordered],y[ordered])
```
```{r}
x<-0:10
y<-0:10
plot(x,y)
lines(x,y,col="red")
lines(x,y,col="blue",type="s")
lines(x,y,col="green",type="S")
```
```{r}
plot(0:10,0:10,xlab="",ylab="",xaxt="n",yaxt="n",type="n")
rect(6,6,9,9)
arrows(1,1,3,8)
arrows(1,9,5,9,code=3)
arrows(4,1,4,6,code=3,angle=90)
polygon(list(x=runif(6), y=runif(6)),col="lavender")
```
```{r}
z <- seq(-3,3,0.01)
pd <- dnorm(z)
plot(z,pd,type="l")
polygon(c(z[z<=-0.5],-0.5),c(pd[z<=-0.5],pd[z==-3]),col="red")
```
```{r}
curve(x^3-3*x, -2, 2)

x <- seq(-2,2,0.01)
y <- x^3-3*x
plot(x,y,type="l")
```
```{r}
xv <- 0:100
yA <- 482*xv*exp(-0.045*xv)
yB <- 518*xv*exp(-0.055*xv)
plot(c(xv,xv),c(yA,yB),xlab="stock",ylab="recruits",type="n")
lines(xv,yA,lty=2,col="blue")
lines(xv,yB,lty=1,col="red")

info <- read.table(file.path(getwd(), "data/plotfit.txt"), header = TRUE)
with(info, points(x, y, pch=16))
```
```{r}
data <- read.table(file.path(getwd(), "data/jaws.txt"), header=TRUE)
par(mfrow=c(2,2))
with(data, {
  plot(age, bone, pch=16, main="lowess")
  lines(lowess(age, bone), col="red")
})

with(data, {
  plot(age, bone, pch=16, main="loess")
  model <- loess(bone ~ age)
  xv <- 0:50
  yv <- predict(model, data.frame(age=xv))
  lines(xv, yv, col="red")
})

library(mgcv)
with(data, {
  plot(age, bone, pch=16, main="gam")
  model <- gam(bone ~ s(age))
  xv <- 0:50
  yv <- predict(model, list(age=xv))
  lines(xv, yv, col="red")
})

with(data, {
  plot(age, bone, pch=16, main="cubic polynomial")
  model <- lm(bone ~ age + I(age ^ 2) + I(age ^ 3))
  xv <- 0:50
  yv <- predict(model, list(age=xv))
  lines(xv, yv, col="red")
})
```
```{r}
data <- read.table(file.path(getwd(), "data/Pollute.txt"), header=TRUE)
#X11(width = 7, height = 4)
par(mfrow=c(1,2))
with(data,{
  plot(Population,Pollution)
  plot(Temp,Pollution)
})
#Sys.sleep(10)
```
```{r}
weather <- read.table(file.path(getwd(), "data/SilwoodWeather.txt"), header=TRUE)
with(weather, plot(as.factor(month), upper, ylab="daily maximum temperature", xlab="month"))
```
```{r}
with(weather, plot(as.factor(month), upper, notch=TRUE, ylab="daily maximum temperature", xlab="month"))
```
```{r}
trial <- read.table(file.path(getwd(), "data/compexpt.txt"), header = TRUE)
means <- tapply(trial$biomass, trial$clipping, mean)
barplot(means, xlab="treatment", ylab="mean yield", col="green")
```
```{r}
seBars <- function(x,y){
  model <- lm(y~factor(x))
  reps <- length(y)/length(levels(x))
  sem <- summary(model)$sigma/sqrt(reps)
  m <- as.vector(tapply(y,x,mean))
  upper <- max(m)+sem
  nn <- as.character(levels(x))
  xs <- barplot(m,ylim=c(0,upper),names=nn,
  ylab=deparse(substitute(y)),xlab=deparse(substitute(x)))
  for (i in 1:length(xs)) {
    arrows(xs[i],m[i]+sem,xs[i],m[i]-sem,angle=90,code=3,length=0.1) 
  }
}
with(trial, seBars(clipping,biomass))
```
```{r}
with(trial,{
  par(mfrow=c(1,2))
  plot(clipping,biomass)
  plot(clipping,biomass,notch=T)
})
```
```{r}
data <- read.table(file.path(getwd(), "data/box.txt"), header=TRUE)
with(data, plot(response~factor(fact),notch=TRUE))
```
```{r}
with(data,{
  index <- order(tapply(response,fact,mean))
  ordered <- factor(rep(index,rep(20,8)))
  boxplot(response~ordered,notch=T,names=as.character(index),
  xlab="ranked treatments",ylab="response")
})
```
```{r}
with(data,{
  model <- aov(response~factor(fact))
  summary(model)
})
```
```{r}
with(data,{
  model <- aov(response~factor(fact))
  summary(model)
  plot(TukeyHSD(model))
})
```

